apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: insights-runtime-extractor
  namespace: openshift-insights
  labels:
    app.kubernetes.io/name: insights-runtime-extractor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: insights-runtime-extractor
  template:
    metadata:
      labels:
        app.kubernetes.io/name: insights-runtime-extractor
      annotations:
        openshift.io/required-scc: insights-runtime-extractor-scc
    spec:
      serviceAccountName: insights-runtime-extractor-sa
      hostPID: true
      # Deploy the insights-runtime-extractor only on Linux worker nodes
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: kube-rbac-proxy
          image: quay.io/openshift/origin-kube-rbac-proxy:latest
          args:
            - '--secure-listen-address=$(IP):8000'
            - '--upstream=http://127.0.0.1:8000'
            - '--config-file=/etc/kube-rbac-proxy/config.yaml'
            - '--tls-cert-file=/etc/tls/private/tls.crt'
            - '--tls-private-key-file=/etc/tls/private/tls.key'
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - mountPath: /etc/tls/private
              name: insights-runtime-extractor-tls
            - mountPath: /etc/kube-rbac-proxy
              name: kube-rbac-proxy-cm
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            runAsNonRoot: true
          env:
            - name: IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          ports:
            - name: https
              containerPort: 8000
              protocol: TCP
        - name: exporter
          image: ghcr.io/jmesnil/insights-runtime-exporter:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /data
              name: data-volume
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
        - name: extractor
          image: ghcr.io/jmesnil/insights-runtime-extractor:latest
          imagePullPolicy: Always
          env:
            - name: CONTAINER_RUNTIME_ENDPOINT
              value: unix:///crio.sock
          securityContext:
            privileged: true
            capabilities:
              drop:
                - ALL
              add:
                - CAP_SYS_ADMIN
          volumeMounts:
            - mountPath: /crio.sock
              name: crio-socket
            - mountPath: /data
              name: data-volume
      volumes:
        - name: crio-socket
          hostPath:
            path: /run/crio/crio.sock
            type: Socket
        - name: data-volume
          emptyDir: {}
        - name: kube-rbac-proxy-cm
          configMap:
            name: kube-rbac-proxy
        - name: insights-runtime-extractor-tls
          secret:
            secretName: insights-runtime-extractor-tls