apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: insights-runtime-extractor
  namespace: openshift-insights
  labels:
    app.kubernetes.io/name: insights-runtime-extractor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: insights-runtime-extractor
  template:
    metadata:
      labels:
        app.kubernetes.io/name: insights-runtime-extractor
    spec:
      serviceAccountName: insights-runtime-extractor-sa
      hostPID: true
      # Deploy the insights-runtime-extractor only on Linux worker nodes
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: insights-runtime-extractor
          # Replace the image field it is is coming from another image registry
          image: ghcr.io/jmesnil/insights-runtime-extractor:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "20Mi"
              cpu: "250m"
          env:
            - name: CONTAINER_RUNTIME_ENDPOINT
              value: unix:///crio.sock
          securityContext:
            privileged: true
            capabilities:
              drop:
                - ALL
              add:
                - CAP_SYS_ADMIN
          volumeMounts:
            - mountPath: /crio.sock
              name: crio-socket
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8000
              scheme: HTTP
      volumes:
        - name: crio-socket
          hostPath:
            path: /run/crio/crio.sock
            type: Socket