---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: insights-runtime-extractor-sa
  namespace: openshift-insights
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: insights-runtime-extractor-role
  namespace: openshift-insights
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - insights-runtime-extractor-scc
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: insights-runtime-extractor-scc
  namespace: openshift-insights
allowHostDirVolumePlugin: true
allowHostPID: true
allowPrivilegedContainer: true
allowedCapabilities:
- CAP_SYS_ADMIN
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
- runtime/default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: insights-runtime-extractor
  namespace: openshift-insights
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: insights-runtime-extractor-role
subjects:
  - kind: ServiceAccount
    name: insights-runtime-extractor-sa